# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
        exclude: "(^|.*/)(dst/.*\\.js|package-lock\\.json)$"
      - id: trailing-whitespace
        # Generated files can have some trailing whitespaces
        exclude: "(^|.*/)(dst/.*\\.js|package-lock\\.json)$"
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=10"]
        # Generated files can get quite big so exclude them from this check.
        exclude: "(^|.*/)(dst/.*\\.js|package-lock\\.json)$"

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        args:
          # Disable shellcheck and pyflakes for now, to enforce consistent behavior.
          - -shellcheck=
          - -pyflakes=

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt

  # Ensure every file has a copyright header as per the Eclipse Foundation's requirements
  - repo: https://github.com/eclipse-score/tooling
    rev: 31ff8eee214e4e97ef8f5cb46e443273515b63ec
    hooks:
      - id: copyright

  - repo: local
    hooks:
      - id: build-setup-qnx-sdp
        name: Build setup-qnx-sdp distribution files
        language: script
        entry: setup-qnx-sdp/build.sh
        files: ^(setup-qnx-sdp/src/.*\.js|setup-qnx-sdp/package\.json)$
        pass_filenames: false
      - id: build-verify-cleanup
        name: Build verify-cleanup distribution files
        language: script
        entry: .github/_internal_actions/verify-cleanup/build.sh
        files: ^(\.github/_internal_actions/verify-cleanup/src/.*\.js|\.github/_internal_actions/verify-cleanup/package\.json)$
        pass_filenames: false
