#!/usr/bin/env node
// Generated by esbuild. Do not edit.
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/launcher.js
var launcher_exports = {};
__export(launcher_exports, {
  findMeasuredCommand: () => findMeasuredCommand,
  findTargetPatterns: () => findTargetPatterns,
  instrumentedArgs: () => instrumentedArgs,
  resolveRealExecutable: () => resolveRealExecutable,
  run: () => run,
  signalExitCode: () => signalExitCode
});
module.exports = __toCommonJS(launcher_exports);
var import_node_child_process = require("node:child_process");
var import_node_fs2 = __toESM(require("node:fs"), 1);
var import_node_path2 = __toESM(require("node:path"), 1);

// src/invocation.js
var import_node_fs = __toESM(require("node:fs"), 1);
var import_node_path = __toESM(require("node:path"), 1);
var INVOCATION_WIDTH = 3;
var MAX_INVOCATIONS = 10 ** INVOCATION_WIDTH;
var MEASURED_COMMANDS = Object.freeze(["build", "run", "test", "coverage"]);
var INVOCATION_FILE_NAMES = Object.freeze({
  executionLog: "execution.log.zst",
  testCache: "test.bep.json",
  profile: "profile.gz"
});
function formatInvocationSequence(sequence) {
  if (!Number.isInteger(sequence) || sequence < 0 || sequence >= MAX_INVOCATIONS) {
    throw new Error(`Invocation sequence must be between 0 and ${MAX_INVOCATIONS - 1}`);
  }
  return sequence.toString().padStart(INVOCATION_WIDTH, "0");
}
function invocationDirectoryName(sequence, command) {
  return `${formatInvocationSequence(sequence)}-${command}`;
}
function invocationFilePaths(directory) {
  return Object.fromEntries(
    Object.entries(INVOCATION_FILE_NAMES).map(([name, fileName]) => [
      name,
      import_node_path.default.join(directory, fileName)
    ])
  );
}
function writeJsonAtomically(filePath, value) {
  const temporaryPath = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  import_node_fs.default.writeFileSync(temporaryPath, `${JSON.stringify(value)}
`);
  import_node_fs.default.renameSync(temporaryPath, filePath);
}
function claimInvocation(root, command, metrics = {}, targets = []) {
  if (!MEASURED_COMMANDS.includes(command)) {
    throw new Error(`Cannot capture unsupported Bazel command '${command}'.`);
  }
  const claims = import_node_path.default.join(root, ".claims");
  import_node_fs.default.mkdirSync(claims, { recursive: true });
  for (let sequence = 0; sequence < MAX_INVOCATIONS; sequence += 1) {
    const formattedSequence = formatInvocationSequence(sequence);
    const claimPath = import_node_path.default.join(claims, `${formattedSequence}.claim`);
    let descriptor;
    try {
      descriptor = import_node_fs.default.openSync(claimPath, "wx");
      import_node_fs.default.writeSync(descriptor, `${process.pid}
`);
    } catch (error) {
      if (error.code === "EEXIST") continue;
      throw error;
    } finally {
      if (descriptor !== void 0) import_node_fs.default.closeSync(descriptor);
    }
    const directory = import_node_path.default.join(root, invocationDirectoryName(sequence, command));
    import_node_fs.default.mkdirSync(directory);
    const files = invocationFilePaths(directory);
    const capturedTargets = Array.isArray(targets) ? targets.filter((target) => typeof target === "string" && target.length > 0) : [];
    const metadata = {
      schemaVersion: 1,
      sequence,
      command,
      targets: capturedTargets,
      startedAt: (/* @__PURE__ */ new Date()).toISOString(),
      finishedAt: null,
      completed: false,
      exitCode: null,
      signal: null,
      metrics: {
        executionLog: Boolean(metrics.executionLog),
        testCache: Boolean(metrics.testCache),
        profile: Boolean(metrics.profile)
      },
      files: Object.fromEntries(
        Object.entries(files).map(([name, filePath]) => [
          name,
          metadataFileName(filePath, Boolean(metrics[name]))
        ])
      )
    };
    const metadataPath = import_node_path.default.join(directory, "metadata.json");
    writeJsonAtomically(metadataPath, metadata);
    return { directory, files, metadata, metadataPath };
  }
  throw new Error(
    "setup-bazel-cache measured invocation limit exceeded: only sequences 000 through 999 are supported."
  );
}
function metadataFileName(filePath, enabled) {
  return enabled ? import_node_path.default.basename(filePath) : null;
}
function finishInvocation(record, exitCode, signal = null) {
  const metadata = {
    ...record.metadata,
    finishedAt: (/* @__PURE__ */ new Date()).toISOString(),
    completed: true,
    exitCode,
    signal,
    outputs: Object.fromEntries(
      Object.entries(record.files).map(([name, filePath]) => [name, import_node_fs.default.existsSync(filePath)])
    )
  };
  writeJsonAtomically(record.metadataPath, metadata);
  return metadata;
}

// src/launcher.js
function findMeasuredCommand(args) {
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === "--") return null;
    if (argument.startsWith("-")) continue;
    if (MEASURED_COMMANDS.includes(argument)) return { command: argument, index };
    return null;
  }
  return null;
}
function findTargetPatterns(args, commandIndex) {
  const targets = [];
  for (const argument of args.slice(commandIndex + 1)) {
    if (argument === "--") break;
    if (argument.startsWith("-")) continue;
    if (argument === "..." || argument.startsWith("//") || argument.startsWith(":") || argument.startsWith("@") && argument.includes("//")) {
      targets.push(argument);
    }
  }
  return targets;
}
function envEnabled(name) {
  return process.env[name]?.trim().toLowerCase() === "true";
}
function resolveRealExecutable(command) {
  const wrapperDirectory = process.env.SETUP_BAZEL_CACHE_LAUNCHER_DIR ? import_node_path2.default.resolve(process.env.SETUP_BAZEL_CACHE_LAUNCHER_DIR) : null;
  for (const entry of (process.env.PATH || "").split(import_node_path2.default.delimiter)) {
    const directory = entry || process.cwd();
    if (wrapperDirectory && import_node_path2.default.resolve(directory) === wrapperDirectory) continue;
    const candidate = import_node_path2.default.join(directory, command);
    try {
      import_node_fs2.default.accessSync(candidate, import_node_fs2.default.constants.X_OK);
      if (import_node_fs2.default.statSync(candidate).isFile()) return candidate;
    } catch {
    }
  }
  throw new Error(`Could not find the underlying '${command}' executable outside the launcher directory.`);
}
function signalExitCode(signal) {
  const signals = { SIGHUP: 1, SIGINT: 2, SIGTERM: 15 };
  return 128 + (signals[signal] || 1);
}
function runProcess(executable, args) {
  return new Promise((resolve) => {
    const child = (0, import_node_child_process.spawn)(executable, args, { stdio: "inherit" });
    const forwardSignals = ["SIGINT", "SIGTERM"].map((signal) => {
      const handler = () => child.kill(signal);
      process.on(signal, handler);
      return [signal, handler];
    });
    let settled = false;
    const finish = (result) => {
      if (settled) return;
      settled = true;
      for (const [name, handler] of forwardSignals) process.removeListener(name, handler);
      resolve(result);
    };
    child.on("error", (error) => {
      console.error(`setup-bazel-cache launcher could not start Bazel: ${error.message}`);
      finish({ code: 127, signal: null });
    });
    child.on("exit", (code, signal) => {
      finish({ code: code ?? signalExitCode(signal), signal });
    });
  });
}
function instrumentedArgs(args, commandIndex, files, metrics = {}) {
  const flags = [];
  if (metrics.executionLog ?? envEnabled("SETUP_BAZEL_CACHE_REPORT_CACHE_HITS")) {
    flags.push(`--execution_log_compact_file=${files.executionLog}`);
  }
  if ((metrics.testCache ?? envEnabled("SETUP_BAZEL_CACHE_REPORT_TEST_CACHE_HITS")) && (files.testCache !== void 0 && files.testCache !== null)) {
    flags.push(
      `--build_event_json_file=${files.testCache}`,
      "--nobuild_event_json_file_path_conversion"
    );
  }
  if (metrics.profile ?? envEnabled("SETUP_BAZEL_CACHE_ENABLE_PROFILING")) {
    flags.push(`--profile=${files.profile}`);
  }
  return [
    ...args.slice(0, commandIndex + 1),
    ...flags,
    ...args.slice(commandIndex + 1)
  ];
}
async function run() {
  const args = process.argv.slice(2);
  const launcherCommand = process.env.SETUP_BAZEL_CACHE_LAUNCHER_COMMAND;
  const commandInfo = findMeasuredCommand(args);
  const root = process.env.SETUP_BAZEL_CACHE_INVOCATION_ROOT;
  const metrics = {
    executionLog: envEnabled("SETUP_BAZEL_CACHE_REPORT_CACHE_HITS"),
    testCache: envEnabled("SETUP_BAZEL_CACHE_REPORT_TEST_CACHE_HITS") && commandInfo?.command !== "build" && commandInfo?.command !== "run",
    profile: envEnabled("SETUP_BAZEL_CACHE_ENABLE_PROFILING")
  };
  const shouldInstrument = Boolean(launcherCommand && commandInfo && root && (metrics.executionLog || metrics.testCache || metrics.profile));
  if (!shouldInstrument) {
    const executable2 = resolveRealExecutable(launcherCommand || "bazel");
    const result2 = await runProcess(executable2, args);
    process.exitCode = result2.code;
    return;
  }
  let record;
  try {
    record = claimInvocation(
      root,
      commandInfo.command,
      metrics,
      findTargetPatterns(args, commandInfo.index)
    );
  } catch (error) {
    console.error(error.message || error);
    process.exitCode = 1;
    return;
  }
  let executable;
  try {
    executable = resolveRealExecutable(launcherCommand);
  } catch (error) {
    finishInvocation(record, 127);
    console.error(error.message || error);
    process.exitCode = 127;
    return;
  }
  const files = invocationFilePaths(record.directory);
  const result = await runProcess(
    executable,
    instrumentedArgs(args, commandInfo.index, files, metrics)
  );
  finishInvocation(record, result.code, result.signal);
  process.exitCode = result.code;
}
if (process.env.SETUP_BAZEL_CACHE_LAUNCHER_RUN === "true") {
  run().catch((error) => {
    console.error(error.stack || error.message || error);
    process.exitCode = 1;
  });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  findMeasuredCommand,
  findTargetPatterns,
  instrumentedArgs,
  resolveRealExecutable,
  run,
  signalExitCode
});
