# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
#
# Composite action to enable the GHA workflow to use the QNX Software Development Platform (SDP) for building and testing software.
# This includes configuring proper access to the licence server by setting the related environment variables for local development
# but also within Bazel by adding some bazel config entries to the file user.bazelrc within the current workspace.
# Additionally allows access to qnx.com by configuring the .netrc file with provided credentials of a specific QNX user account.
#
# Recommended default usage with mandatory input params:
#
# - name: Setup qnx
#   uses: eclipse-score/cicd-actions/.github/actions/setup-qnx-sdp@<git sha1>
#   with:
#     qnx_license: ${{ secrets.QNX_LICENSE }}
#     qnx_user: ${{ secrets.QNX_USER }}
#     qnx_password: ${{ secrets.QNX_PASSWORD }}
#     qnx_license_server: ${{ vars.QNX_LICENSE_SERVER }}
#
#  Optional parameters are:
#     qnx_license_dir    # default: "/opt/qnx/license"
#     qnx_license_server # optional, if not provided no license server will be configured
#

name: Setup QNX SDP
description: Setup runner environment for using QNX SDP, including licence server configuration.

inputs:
  qnx_license:
    description: "Base64 encoded content of the QNX client license file. Value will be masked in all workflow logs!"
    required: true
  qnx_license_dir:
    description: "Directory where the QNX client license file will be stored. If the path starts with '/' then
                  sudo permissions are required when running this action. To store it somewhere in the home folder use '~/...' as path."
    required: true
    default: "/opt/qnx/license"
  qnx_user:
    description: "Username of the QNX user account for accessing qnx.com. Value will be masked in all workflow logs!"
    required: true
  qnx_password:
    description: "Password of the QNX user account for accessing qnx.com. Value will be masked in all workflow logs!"
    required: true
  qnx_license_server:
    description: "Address of the QNX license server (e.g. '6287@license-server-hostname'). If not provided, no license server will be configured."
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure secrets to be masked in logs
      shell: bash
      env:
        QNX_LICENSE: ${{ inputs.qnx_license }}
        QNX_USER: ${{ inputs.qnx_user }}
        QNX_PASSWORD: ${{ inputs.qnx_password }}
      run: |
        echo "::group::  Configure secrets to be masked in logs"

        set -euo pipefail

        echo "Masking secrets in logs: QNX_PASSWORD, QNX_USER, QNX_LICENSE"
        echo "::add-mask::$QNX_LICENSE"
        echo "::add-mask::$QNX_USER"
        echo "::add-mask::$QNX_PASSWORD"

        echo "::endgroup::"

    - name: Prepare QNX license file
      shell: bash
      env:
        QNX_LICENSE: ${{ inputs.qnx_license }}
        LICENSE_DIR: ${{ inputs.qnx_license_dir }}
        # Assuming that if license dir starts with "/" it is a system folder that needs sudo for access.
        SUDO: |-
          ${{ case(
            startsWith(inputs.qnx_license_dir, '/'), 'sudo',
            ''
          ) }}
      run: |
        echo "::group::  Prepare QNX license file"

        set -euo pipefail

        # replace tilde by $HOME since the tilde char makes problems in github actions
        LICENSE_DIR="${LICENSE_DIR/#\~/$HOME}"

        ${SUDO} mkdir -p "${LICENSE_DIR}"
        echo "${QNX_LICENSE}" | base64 --decode | ${SUDO} tee "${LICENSE_DIR}/licenses" >/dev/null
        # Set permissions to be readable for all users, otherwise the runner user might not be able to consume the license if the license file is stored in a
        # system folder that requires sudo for access. Also if this file content is somehow compromised it does not help the attacker/thief because they are not
        # allowed to access the license server.
        ${SUDO} chmod 644 "${LICENSE_DIR}/licenses"

        echo "Prepared license file is located here:"
        ${SUDO} ls -l "${LICENSE_DIR}/licenses"

        echo "::endgroup::"

    - name: Configure qnx license server
      if: ${{ inputs.qnx_license_server != '' }}
      shell: bash
      env:
        QNX_LICENSE_SERVER: ${{ inputs.qnx_license_server }}
      run: |
        export QNX_LICENSE_EXTSERVER_DELAY=59
        export QNX_LICENSE_QUEUE_TIMEOUT=60
        echo "QNXLM_LICENSE_FILE=${QNX_LICENSE_SERVER}" >> $GITHUB_ENV
        echo "QNX_LICENSE_EXTSERVER_DELAY=${QNX_LICENSE_EXTSERVER_DELAY}" >> $GITHUB_ENV
        echo "QNX_LICENSE_QUEUE_TIMEOUT=${QNX_LICENSE_QUEUE_TIMEOUT}" >> $GITHUB_ENV
        echo "build --action_env=QNXLM_LICENSE_FILE=${QNX_LICENSE_SERVER} --action_env=QNX_LICENSE_EXTSERVER_DELAY --action_env=QNX_LICENSE_QUEUE_TIMEOUT" >> user.bazelrc
        # In case the tests are also executing tools from the QNX sdp that require a license then also set these env vars for the test execution environment
        echo "build --test_env=QNXLM_LICENSE_FILE=${QNX_LICENSE_SERVER} --test_env=QNX_LICENSE_EXTSERVER_DELAY --test_env=QNX_LICENSE_QUEUE_TIMEOUT" >> user.bazelrc
        # Required as the bazel qnx toolchain configures /var/tmp/.qnx as QNX_CONFIGURATION_EXCLUSIVE env var. In this folder
        #    license related metadata files need to be stored during the build and therefore it needs to be writable.
        # Set /var/tmp as writable because /var/tmp/.qnx might not be existing when Bazel starts
        echo "common --sandbox_writable_path=/var/tmp" >> user.bazelrc

    - name: Configure access to qnx.com via .netrc
      uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 #v3.0.0
      with:
        machine: qnx.com
        username: ${{ inputs.qnx_user }}
        password: ${{ inputs.qnx_password }}
